/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class weka_filters_supervised_attribute_CAIMGPU */

#ifndef _Included_weka_filters_supervised_attribute_CAIMGPU
#define _Included_weka_filters_supervised_attribute_CAIMGPU
#ifdef __cplusplus
extern "C" {
#endif
#undef weka_filters_supervised_attribute_CAIMGPU_serialVersionUID
#define weka_filters_supervised_attribute_CAIMGPU_serialVersionUID -8835063755891851218LL
#undef weka_filters_supervised_attribute_CAIMGPU_serialVersionUID
#define weka_filters_supervised_attribute_CAIMGPU_serialVersionUID 1LL
#undef weka_filters_supervised_attribute_CAIMGPU_serialVersionUID
#define weka_filters_supervised_attribute_CAIMGPU_serialVersionUID 1LL
/*
 * Class:     weka_filters_supervised_attribute_CAIMGPU
 * Method:    initializeGPU
 * Signature: (Lweka/filters/supervised/attribute/CAIMGPU;IIII)V
 */
JNIEXPORT void JNICALL Java_weka_filters_supervised_attribute_CAIMGPU_initializeGPU
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
